"""
Extract current Event IDs and Commence Times from Events data.

This script reads current events data from Google Cloud Storage
that was generated by events.py and extracts all event IDs and
their commence times, then saves them to storage for use by other processes.

Path Structure:
- Bucket: SMARTBETTING_STORAGE
- Season: SEASON_2025
- Input Path: odds/events/season_2025/
- Output Path: odds/event_id/season_2025/
"""

import sys
import os
from datetime import date

# Add the project root to the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from lib_dev.smartbetting import SmartbettingLib
from lib_dev.utils import Bucket, Catalog, Table, Season


def main():
    """
    Main function to extract and save current event IDs and commence times.
    """
    # Initialize API client
    smartbetting = SmartbettingLib()
    
    # Configuration
    bucket = Bucket.SMARTBETTING_STORAGE
    catalog = Catalog.ODDS
    season = Season.SEASON_2025
    input_table = Table.EVENTS
    output_table = Table.EVENT_ID
    
    # Parameters
    start_date = None
    end_date = None
    target_date = None  # Will default to today if None

    print("Extracting current event IDs and commence times...")
    
    # Extract event IDs from current events data
    event_data = smartbetting.extract_event_ids_from_events_data(
        bucket_name=str(bucket),
        catalog=str(catalog),
        table=str(input_table),
        season=str(season),
        start_date=start_date,
        end_date=end_date,
    )

    if not event_data:
        print("❌ No event data found")
        return

    # Save event IDs to storage
    saved_path = smartbetting.save_event_ids_to_storage(
        event_data=event_data,
        bucket_name=str(bucket),
        catalog=str(catalog),
        table=str(output_table),
        season=str(season),
        target_date=target_date,
    )

    if saved_path:
        print(f"✅ Successfully processed {len(event_data)} events")
        print(f"📁 Saved to: {saved_path}")
        
        # Show sample events
        sample_items = list(event_data.items())[:3]
        print("\nSample events:")
        for i, (event_id, commence_time) in enumerate(sample_items, 1):
            print(f"{i}. ID: {event_id[:20]}... | Commence: {commence_time}")
    else:
        print("❌ Failed to save event data to storage")


if __name__ == "__main__":
    main()


