version: 2

sources:
  - name: nba
    description: "NBA data from external tables in Google Cloud Storage"
    tables:
      - name: raw_teams
        description: "NBA teams raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landing/nba/teams/raw_nba_teams.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: id
            description: "Unique team identifier"
            data_type: integer
          - name: name
            description: "Team name"
            data_type: string
          - name: full_name
            description: "Team full name"
            data_type: string
          - name: abbreviation
            description: "Team abbreviation"
            data_type: string
          - name: city
            description: "Team city"
            data_type: string
          - name: conference
            description: "Conference (Eastern or Western)"
            data_type: string
          - name: division
            description: "Division within conference"
            data_type: string

      - name: raw_active_players
        description: "NBA active players raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landing/nba/active_players/raw_nba_active_players.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: id
            description: "Unique player identifier"
            data_type: integer
          - name: first_name
            description: "Player first name"
            data_type: string
          - name: last_name
            description: "Player last name"
            data_type: string
          - name: position
            description: "Player position"
            data_type: string
          - name: height
            description: "Player height"
            data_type: string
          - name: weight
            description: "Player weight"
            data_type: string
          - name: jersey_number
            description: "Player jersey number"
            data_type: string
          - name: college
            description: "Player college"
            data_type: string
          - name: country
            description: "Player country"
            data_type: string
          - name: draft_year
            description: "Draft year"
            data_type: integer
          - name: draft_round
            description: "Draft round"
            data_type: integer
          - name: draft_number
            description: "Draft number"
            data_type: integer
          - name: team
            description: "Player team information (STRUCT with id, name, abbreviation, etc.)"
            data_type: struct

      - name: raw_team_standings
        description: "NBA team standings raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landing/nba/team_standings/raw_nba_team_standings.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: team
            description: "Team information (STRUCT with id, name, abbreviation, conference, division, etc.)"
            data_type: struct
          - name: conference_record
            description: "Conference record (e.g., '10-1')"
            data_type: string
          - name: conference_rank
            description: "Rank within conference"
            data_type: integer
          - name: division_record
            description: "Division record (e.g., '5-0')"
            data_type: string
          - name: division_rank
            description: "Rank within division"
            data_type: integer
          - name: wins
            description: "Total number of wins"
            data_type: integer
          - name: losses
            description: "Total number of losses"
            data_type: integer
          - name: home_record
            description: "Home games record (e.g., '8-0')"
            data_type: string
          - name: road_record
            description: "Away games record (e.g., '2-1')"
            data_type: string
          - name: season
            description: "Season year"
            data_type: integer

      - name: raw_season_averages_general_advanced
        description: "NBA season averages general advanced raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landing/nba/season_averages/general/advanced/*/*/season_averages_general_advanced_*.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: player
            description: "Player information (STRUCT with id, first_name, last_name, position, height, weight, etc.)"
            data_type: struct
          - name: season
            description: "Season year (e.g., 2024)"
            data_type: integer
          - name: season_type
            description: "Season type (regular, playoffs, ist, playin)"
            data_type: string
          - name: stats
            description: "Season statistics (STRUCT with various statistical fields based on category/type)"
            data_type: struct

      - name: raw_games
        description: "NBA games raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landing/nba/games/raw_nba_games_*.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: id
            description: "Unique game identifier"
            data_type: integer
          - name: date
            description: "Game date (YYYY-MM-DD)"
            data_type: string
          - name: season
            description: "Season year (e.g., 2018)"
            data_type: integer
          - name: status
            description: "Game status (e.g., Final, InProgress, Scheduled)"
            data_type: string
          - name: period
            description: "Current period/quarter (0-4)"
            data_type: float
          - name: time
            description: "Time remaining in period"
            data_type: string
          - name: postseason
            description: "Whether the game is a postseason game"
            data_type: boolean
          - name: home_team_score
            description: "Home team final score"
            data_type: float
          - name: visitor_team_score
            description: "Visitor team final score"
            data_type: float
          - name: home_team
            description: "Home team information (STRUCT with id, name, abbreviation, conference, division, etc.)"
            data_type: struct
          - name: visitor_team
            description: "Visitor team information (STRUCT with id, name, abbreviation, conference, division, etc.)"
            data_type: struct

      - name: raw_game_player_stats
        description: "NBA game player stats raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landing/nba/game_player_stats/raw_nba_game_player_stats_*.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: id
            description: "Unique stat record identifier"
            data_type: float
          - name: min
            description: "Minutes played (as string)"
            data_type: string
          - name: fgm
            description: "Field goals made"
            data_type: float
          - name: fga
            description: "Field goals attempted"
            data_type: float
          - name: fg_pct
            description: "Field goal percentage"
            data_type: float
          - name: fg3m
            description: "Three-pointers made"
            data_type: float
          - name: fg3a
            description: "Three-pointers attempted"
            data_type: float
          - name: fg3_pct
            description: "Three-point percentage"
            data_type: float
          - name: ftm
            description: "Free throws made"
            data_type: float
          - name: fta
            description: "Free throws attempted"
            data_type: float
          - name: ft_pct
            description: "Free throw percentage"
            data_type: float
          - name: oreb
            description: "Offensive rebounds"
            data_type: float
          - name: dreb
            description: "Defensive rebounds"
            data_type: float
          - name: reb
            description: "Total rebounds"
            data_type: float
          - name: ast
            description: "Assists"
            data_type: float
          - name: stl
            description: "Steals"
            data_type: float
          - name: blk
            description: "Blocks"
            data_type: float
          - name: turnover
            description: "Turnovers"
            data_type: float
          - name: pf
            description: "Personal fouls"
            data_type: float
          - name: pts
            description: "Points scored"
            data_type: float
          - name: player
            description: "Player information (STRUCT with id, first_name, last_name, position, etc.)"
            data_type: struct
          - name: team
            description: "Team information (STRUCT with id, name, abbreviation, conference, division, etc.)"
            data_type: struct
          - name: game
            description: "Game information (STRUCT with id, date, season, status, etc.)"
            data_type: struct

      - name: raw_leaders
        description: "NBA leaders raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landing/nba/leaders/raw_nba_leaders_*.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: player
            description: "Player information (STRUCT with id, first_name, last_name, position, etc.)"
            data_type: struct
          - name: team
            description: "Team information (STRUCT with id, name, abbreviation, conference, division, etc.)"
            data_type: struct
          - name: season
            description: "Season year"
            data_type: integer
          - name: stat_type
            description: "Type of statistical category"
            data_type: string
          - name: value
            description: "Statistical value"
            data_type: float 